# Generated by Django 5.2.17 on 2026-09-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='note',
            new_name='notes',
        ),
    ]
